configurators/src/main/java/org/jahia/configuration/configurators/JahiaGlobalConfigurator.java

https://jira.jahia.org/browse/TECH-201
If jahia.node.properties is not found in -ee (or -ee is not found), look into jahia-impl.jar before fallbacking on jahia-default-config

TECH-201: Look for properties file in both impl and -ee jars

---

maven-jahia-plugin/pom.xml
maven-jahia-plugin/src/test/java/org/jahia/utils/maven/plugin/osgi/BuildFrameworkPackageListMojoTest.java
pom.xml

https://jira.jahia.org/browse/BACKLOG-15893
Updating libs for security issues

BACKLOG-15893: update dependencies

---

maven-jahia-plugin/pom.xml
maven-jahia-plugin/src/main/java/org/jahia/utils/maven/plugin/DeployMojo.java

https://jira.jahia.org/browse/BACKLOG-15593

BACKLOG-15593: Chown to tomcat user

---

configurators/src/main/java/org/jahia/configuration/configurators/JackrabbitConfigurator.java
configurators/src/main/java/org/jahia/configuration/configurators/JahiaConfigBean.java
configurators/src/main/java/org/jahia/configuration/configurators/JahiaConfigInterface.java
configurators/src/main/java/org/jahia/configuration/configurators/JahiaGlobalConfigurator.java
maven-jahia-plugin/src/main/java/org/jahia/utils/maven/plugin/buildautomation/ConfigureMojo.java

BACKLOG-16727
Just add the jahia.configure.storeFilesInAWS parameter , remove other datastores from repository.xml

BACKLOG-16727 : Add S3Datasource support

---

configurators/pom.xml

https://jira.jahia.org/browse/QA-14073
Bring back xerces dependency to fix NPE in CopyTemplatesMojo

QA-14073: Bring back xerces dependency

---

maven-jahia-plugin/src/main/java/org/jahia/utils/maven/plugin/CopyTemplatesMojo.java
pom.xml

https://jira.jahia.org/browse/QA-14073

QA-14073: restore enableLogging setup to avoid NPE while deploying

---

maven-jahia-plugin/pom.xml
maven-jahia-plugin/src/main/java/org/jahia/utils/maven/plugin/osgi/DependenciesMojo.java
maven-jahia-plugin/src/main/java/org/jahia/utils/maven/plugin/support/Maven31AetherHelper.java

…
https://jira.jahia.org/browse/FORM-1737
The following are included in this PR
I have considered the following implications of my change:

FORM-1737: Do not use deprecated code anymore and avoid calling collectDependencies to try resolving/downloading the world

---

maven-jahia-plugin/src/main/java/org/jahia/utils/maven/plugin/osgi/CheckDependenciesMojo.java
maven-jahia-plugin/src/main/java/org/jahia/utils/maven/plugin/osgi/DependenciesMojo.java
maven-jahia-plugin/src/main/java/org/jahia/utils/maven/plugin/support/Maven31AetherHelper.java
maven-jahia-plugin/src/main/resources/org/jahia/utils/maven/plugin/osgi/dependencies.properties

https://jira.jahia.org/browse/TECH-241

TECH-241 : simplify plugin, improve optional imports 

---

configurators/pom.xml

https://jira.jahia.org/browse/TECH-979
Upgrade DB drivers

TECH-979: Upgrade db drivers

---

configurators/src/main/java/org/jahia/configuration/configurators/JahiaPropertiesConfigurator.java

https://jira.jahia.org/browse/QA-14386

QA-14386: don't set jahiaToolManagerUsername if not needed

---

maven-jahia-plugin/src/main/java/org/jahia/utils/maven/plugin/osgi/DependenciesMojo.java

https://jira.jahia.org/browse/QA-14548
The following are included in this PR
I have considered the following implications of my change:

QA-14548: ensure we use a new cache for newest DependenciesMojo

---

configurators/pom.xml
maven-jahia-plugin/pom.xml

https://jira.jahia.org/browse/QA-14589

QA-14589: Fixed  dependencies to commons-text

---

configurators/pom.xml

https://jira.jahia.org/browse/BACKLOG-20480
PosgreSQL: https://github.com/Jahia/jahia-private/pull/1495
MySQL: https://github.com/Jahia/jahia-private/pull/1496 
MariaDB: https://github.com/Jahia/jahia-private/pull/1498

BACKLOG-20480 - Upgrade DB drivers

---

configurators/pom.xml

https://jira.jahia.org/browse/BACKLOG-20608

BACKLOG-20608 -Revert upgrade to minor version of MariaDB

---

configurators/pom.xml

https://jira.jahia.org/browse/BACKLOG-20691

BACKLOG-20691 - Update MariaDB version to 3.0.9

---

maven-jahia-plugin/pom.xml

https://jira.jahia.org/browse/TECH-1256
Upgrade Xalan from 2.7.2 to 2.7.3
The following are included in this PR
I have considered the following implications of my change:

TECH-1256: Upgrade Xalan

---

configurators/pom.xml

This reverts commit 43d5030e09b6f40170406b502efd2fa2c3a89a08.
https://jira.jahia.org/browse/BACKLOG-20795

Revert "BACKLOG-20795: Update db drivers (#65)"

---

configurators/pom.xml

https://jira.jahia.org/browse/BACKLOG-20795

BACKLOG-20795 - Add back mysql/oracle/postgresql updates

---

configurators/pom.xml

https://jira.jahia.org/browse/BACKLOG-20795
Unsigned jar uploaded to thirdparty-releases maven repo as per https://confluence.jahia.com/display/PR/Upgrading+JDBC+drivers+in+DX
Related PR: https://github.com/Jahia/jahia-private/pull/1604

BACKLOG-20795: Update mssql driver version

---

maven-jahia-plugin/src/main/java/org/jahia/utils/maven/plugin/osgi/CheckDependenciesMojo.java

https://jira.jahia.org/browse/TECH-1009

TECH-1009: Fix import-package version override

---

jahia-simple-maven-plugin/pom.xml
jahia-simple-maven-plugin/src/main/java/org/jahia/utils/maven/plugin/AbstractManagementMojo.java
jahia-simple-maven-plugin/src/main/java/org/jahia/utils/maven/plugin/MojoLogger.java
jahia-simple-maven-plugin/src/main/java/org/jahia/utils/maven/plugin/buildautomation/ConfigureMojo.java
pom.xml

https://jira.jahia.org/browse/TECH-1405
This is a copy of the jahia-maven-plugin with the configure goal only, which is the only goal required to start jahia image. Remove all unnecessary dependencies.

TECH-1405: plugin for docker image with less goals and dependencies

---

configurators/pom.xml

https://jira.jahia.org/browse/SEC-51

SEC-51 : update org.json version

---

maven-jahia-plugin/src/main/java/org/jahia/utils/maven/plugin/osgi/CheckDependenciesMojo.java

https://jira.jahia.org/browse/BACKLOG-22362
Fix NPE when package coming from bnd do not have version

BACKLOG-22362: fix null pointer exception

---

configurators/pom.xml

https://jira.jahia.org/browse/BACKLOG-21153

BACKLOG-21153: Update DB drivers versions

---

configurators/pom.xml

https://jira.jahia.org/browse/BACKLOG-22439 
https://jira.jahia.org/browse/BACKLOG-21153
Revert this upgrade as it's causing an issue in the logs preventing many Selenium test to be executed

BACKLOG-22439 BACKLOG-21153: Revert MariaDB driver upgrade

---

.github/workflows/schedule-sonar.yml

https://jira.jahia.org/browse/TECH-1739

TECH-1739: Create schedule-sonar.yml

---

configurators/pom.xml

https://jira.jahia.org/browse/BACKLOG-22951

BACKLOG-22951: Update drivers versions for 8.1.8.0

---

.github/maven.settings.xml
.github/workflows /on-code-change.yml
.github/workflows /on-merge.yml

https://jira.jahia.org/browse/BACKLOG-22951

BACKLOG-22951: Create CI/CD config

---

configurators/pom.xml
deployers/src/main/java/org/jahia/configuration/deployers/jboss/DriverDeploymentHelper.java
maven-jahia-plugin/src/main/java/org/jahia/utils/maven/plugin/jarscan/JarsToSkipListMojo.java

...
The following are included in this PR
I have considered the following implications of my change:

chore: updated JDBC drivers for 8.2.1.0 release

---

.github/workflows/on-merge.yml

Upload sbom-artifacts after build - to be picked up by the sbom-processing 
> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)

fix: upload sbom-artifacts after build
